### ISSUE TITLE
Pyppeteer Error

### ISSUE THREAD

**Issue by StAnthonys** [evmer/perlego-downloader#12]
Hi there,

Im having issues with pdf books. so far all epubs work well.

Book ID is 3361318, and a folder is created with all the downloaded pages in html format, however error comes up before it converts to the hmtls to pdf and stitches it all together.

I also had to update line 19 (PUPPETEER_THREADS = 50) to 400. not sure, but it was originally only outputting the first 50 pages to html. I have used both 50 and 400 still no effect, but atleast all 255 pages are output as html, rather than just the first 50.

this is the last part that  MacOSX terminal outputs.
----------
page 221-222 downloaded
page 222-223 downloaded
page 223-224 downloaded
page 224-225 downloaded
Traceback (most recent call last):
  File "/Users/Moon/Desktop/Perlego-Downloader/perlego-downloader-main/downloader.py", line 242, in <module>
    asyncio.run(html2pdf())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/Moon/Desktop/Perlego-Downloader/perlego-downloader-main/downloader.py", line 238, in html2pdf
    await asyncio.gather(*[render_page(chapter_no, sem) for chapter_no in contents])
  File "/Users/Moon/Desktop/Perlego-Downloader/perlego-downloader-main/downloader.py", line 221, in render_page
    await page.goto(f'file://{cache_dir}/{chapter_no}.html', {"waitUntil" : ["load", "domcontentloaded", "networkidle0", "networkidle2"]})
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pyppeteer/page.py", line 837, in goto
    raise error
pyppeteer.errors.TimeoutError: Navigation Timeout Exceeded: 30000 ms exceeded.

--------

**Comment by dimoca** [comment]
Hello,

I have the same problem with the book ID 3263780 with 163 pages, I end up with the same error... and I can't find the solution.

**Comment by evmer** [comment]
It should be a temporary network error. Have you tried to restart the script?

**Comment by dimoca** [comment]
> It should be a temporary network error. Have you tried to restart the script?

Yes, but the problem persists.  There is no way to make it finish successfully.  The html if you lls download all it is when you pass them to pdf when the error arrives.

**Comment by evmer** [comment]
I can't replicate this issue. Download of book ID 3263780 works fine for me:

<img width="1558" alt="image" src="https://user-images.githubusercontent.com/10036897/193451327-36c7224c-b887-4890-b947-87fd622f512a.png">

Anyway, I just applied a small patch to handle the network errors during the PDF parsing, hope it helps.
