### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by lilfmdude** [evmer/perlego-downloader#9]
I have downloaded the new script but I'm still getting errors also the book id I'm trying is 1323963 maybe it has something to do with it? I do not know hope this helps you.
![image](https://user-images.githubusercontent.com/34497266/189736536-d11d6607-6ba4-450a-949c-1cbbe9020cbc.png)

**Comment by evmer** [comment]
Hello, same issue of #8 

Did you follow [these troubleshoot guidelines](https://github.com/evmer/perlego-downloader#troubleshoot)?

**Comment by lilfmdude** [comment]
yes i just double checked book id and the auth is correct i even pasted it again just incase same error

**Comment by evmer** [comment]
@lilfmdude the issue is not related to the book id or auth params, but to a misconfiguration of puppeeter/chrome driver dependences. Please follow these instructions:

<img width="877" alt="image" src="https://user-images.githubusercontent.com/10036897/189737851-55efe8f2-610c-4376-a559-8ae6d915a275.png">

**Comment by lilfmdude** [comment]
can you give me a detail instructions on how to add it to my system path? or do i just added with the same perlego downloader?

**Comment by evmer** [comment]
> can you give me a detail instructions on how to add it to my system path? or do i just added with the same perlego downloader?

Download the latest version of chromedriver.exe [here](https://chromedriver.chromium.org/downloads) and place it in C:/Windows.

**Comment by lilfmdude** [comment]
did exactly as you said still getting same error

**Comment by evmer** [comment]
> did exactly as you said still getting same error

You can try to follow [this answer](https://stackoverflow.com/a/62305560/388951) on stackoverflow and debug pyppeteer by yourself. Pop up the terminal, run `python` to open the command-line interpreter and then:

```
>>> from pyppeteer.launcher import Launcher
>>> ' '.join(Launcher().cmd)
```

Copy the result, exit from the python interpreter with `exit()`, paste the command in the terminal and run it. You should see the error that prevents pyppeeter from launching properly (maybe some missing dependences).

**Comment by lilfmdude** [comment]
this is what i get when pressing enter after inputting that command
![image](https://user-images.githubusercontent.com/34497266/189745170-11ec6fce-653f-4dc5-aaee-ebef33d6869e.png)

**Comment by evmer** [comment]
@lilfmdude copy-paste the commands without the `>>>`

**Comment by lilfmdude** [comment]
![image](https://user-images.githubusercontent.com/34497266/189745887-52f3a0d4-e32f-4798-bfbe-0e99acbf8ab3.png)
this is what i get

**Comment by evmer** [comment]
@lilfmdude 

> Copy the result, exit from the python interpreter with exit(), paste the command in the terminal and run it. You should see the error that prevents pyppeeter from launching properly (maybe some missing dependences).

**Comment by lilfmdude** [comment]
like this? 
![image](https://user-images.githubusercontent.com/34497266/189746908-5862de65-e8d7-4598-9568-92599964f990.png)

**Comment by evmer** [comment]
@lilfmdude No...you're not following the instructions. Please read carefully what I wrote and try again.

**Comment by lilfmdude** [comment]
sorry, when you say terminal you do you mean on the visual terminal? and if so if not i have no idea
![image](https://user-images.githubusercontent.com/34497266/189750060-e2759def-982c-48c5-884a-1e36c3b73344.png)

**Comment by lilfmdude** [comment]
hey so i got it to work i just installed a vm workstation slapped linux on it and it just worked first try thanks man! i guess its just windows side its just not working i don't know

**Comment by Noiade** [comment]
> sorry, when you say terminal do you mean on the visual terminal? and if so if not i have no idea ![image](https://user-images.githubusercontent.com/34497266/189750060-e2759def-982c-48c5-884a-1e36c3b73344.png)

Same for me. Reinstalled chromium several times. Put chromedriver to C:\WINDOWS. Chrome and pypeeter work perfectly. But the script does not:

C:\Users\forsite\Documents\perlego-downloader-main>C:\\Users\\forsite\\AppData\\Local\\pyppeteer\\pyppeteer\\local-chromium\\588429\\chrome-win32\\chrome.exe --disable-background-networking --disable-background-timer-throttling --disable-breakpad --disable-browser-side-navigation --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=site-per-process --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-translate --metrics-recording-only --no-first-run --safebrowsing-disable-auto-update --enable-automation --password-store=basic --use-mock-keychain --headless --hide-scrollbars --mute-audio --disable-gpu about:blank --remote-debugging-port=51505 --user-data-dir=C:\\Users\\kolomenskiy_pi\\AppData\\Local\\pyppeteer\\pyppeteer\\.dev_profile\\tmpjor6j0j5
C:\Users\forsite\Documents\perlego-downloader-main>

Still:

Traceback (most recent call last):
  File "C:\Users\kolomenskiy_pi\Documents\Personal\The Family Business Map\perlego-downloader-main\downloader.py", line 244, in <module>
    asyncio.run(html2pdf())
  File "C:\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\kolomenskiy_pi\Documents\Personal\The Family Business Map\perlego-downloader-main\downloader.py", line 165, in html2pdf
    browser = await launch(options={
  File "C:\Python310\lib\site-packages\pyppeteer\launcher.py", line 307, in launch
    return await Launcher(options, **kwargs).launch()
  File "C:\Python310\lib\site-packages\pyppeteer\launcher.py", line 168, in launch
    self.browserWSEndpoint = get_ws_endpoint(self.url)
  File "C:\Python310\lib\site-packages\pyppeteer\launcher.py", line 227, in get_ws_endpoint
    raise BrowserError('Browser closed unexpectedly:\n')
pyppeteer.errors.BrowserError: Browser closed unexpectedly:


I can send EVMER my downloader file (with BOOK and AUTH inserted) so as you could troubleshoot and/or simply download the book for me.

**Comment by Noiade** [comment]
> > did exactly as you said still getting same error
> 
> You can try to follow [this answer](https://stackoverflow.com/a/62305560/388951) on stackoverflow and debug pyppeteer by yourself. Pop up the terminal, run `python` to open the command-line interpreter and then:
> 
> ```
> >>> from pyppeteer.launcher import Launcher
> >>> ' '.join(Launcher().cmd)
> ```
> 
> Copy the result, exit from the python interpreter with `exit()`, paste the command in the terminal and run it. You should see the error that prevents pyppeeter from launching properly (maybe some missing dependences).

Hello there! This solution helped me to troubleshoot under WSL/ubuntu and let pyppeteer work. So I managed to download the book finally - everything worked well.

Thanks a lot

**Comment by cotagxrdhy** [comment]
Hi,I'm having the same problem, has anyone solved the problem on Windows ?

I followed the instructions to troubleshoot everything, but it still doesn't work

**Comment by josema2242** [comment]
help me please I tried in ubuntu but it gave me an error

**Comment by enDanac33** [comment]
I get this error

o@o-B250M-DS3H:~/Escritorio$ python3 downloader.py
download error: Connection timed out
download error: Connection timed out
download error: Connection timed out
download error: Connection timed out
download error: Connection timed out
download error: Connection timed out
download error: Connection timed out

**Comment by pandamoon21** [comment]
> I get this error
> 
> o@o-B250M-DS3H:~/Escritorio$ python3 downloader.py download error: Connection timed out download error: Connection timed out download error: Connection timed out download error: Connection timed out download error: Connection timed out download error: Connection timed out download error: Connection timed out

I got this error too, but after I use an account with an active subscription. It's starting to download.

**Comment by Moanrisy** [comment]
I got this bug too. Already reinstall chrome, put chromedriver on env PATH C:/Windows. None of this working.
Now I will try WSL ubuntu.

**Comment by Moanrisy** [comment]
![image](https://user-images.githubusercontent.com/17421945/202200752-8f2d5109-efbe-4758-a43f-ade9ec92b825.png)

And I still got the error :'(

**Comment by Moanrisy** [comment]
Finally it work after reading this
https://stackoverflow.com/a/71935536/10486986

**Comment by cezarlacatus** [comment]
Solved on windows by installing official chrome and pointing Pupeteer to use it like this

```
			'headless': True,
			'autoClose': False,
			'executablePath': 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
```
So modify line 171.

**Comment by evmer** [comment]
Thank you @cezarlacatus ! 🎉 Seems you have fixed one of the most frequent bugs here. I'm going to add your suggestion to the README.
